### PR TITLE
start docs

### PR DESCRIPTION
**Pull request by stchang**
Just a stub at the moment

UPDATE: rough draft of `racketscript/interop`: https://stchang.github.io/racketscript/

### CODE REVIEW

**Comment by stchang** [comment]
related: https://github.com/vishesh/racketscript/issues/210

**Comment by stchang** [comment]
@gamburgm @daynin @vishesh Starting this to get the infrastructure in place. I'm working on ffi docs right now but let me know if you want to add a section.

(@daynin Did you already start some docs? Just want to make sure we are not duplicating work)

**Comment by stchang** [comment]
rendered: https://stchang.github.io/racketscript/

**Comment by stchang** [comment]
pushed a very rough draft, in case anyone wants to take a look: https://stchang.github.io/racketscript

(Definitely ened more examples. And I dont know why the symbols arent rendering properly.)

**Comment by daynin** [comment]
> (@daynin Did you already start some docs? Just want to make sure we are not duplicating work)

No, I haven't done it yet

**Comment by stchang** [comment]
updated and polished ffi docs, e.g., added reader extensions: https://stchang.github.io/racketscript/

**Comment by stchang** [comment]
> > (@daynin Did you already start some docs? Just want to make sure we are not duplicating work)
> 
> No, I haven't started yet

No worries. Feel free to add to, or make suggestions on what I started here

**Comment by stchang** [comment]
I think I'm done with the FFI docs. Should we merge first and then open another ticket for other docs. Or to just keep this ticket open?

**Review by vishesh — APPROVED** [review]

**Pull request merged**
