### PR TITLE
Allow for `#f` default value

### LINKED ISSUE #252: make-vector default value doesnt allow false
`(make-vector 3 #f)` should evaluate to a vector of false values but instead it mistakenly uses the default `0` value

http://play.racketscript.org/#gist/c5fc2837855bbebacea191f255b5a251

### PR DESCRIPTION
**Pull request by gamburgm**
Fixes #252.

Previously, if the default value provided to `make-vector` was falsey, the vector would be populated with `0`. Now this will only happen if the default value is `undefined`.

If we wanted to enable a developer to populate a vector with `undefined`, we'd have to be able to detect if a value was passed in to the function or not. We could do so by accessing `arguments` directly if we feel like this is something a user should be able to do. 

As an addendum, even though `kernel.rkt` is enormous, might still be good to create a test submodule and throw things in there as people modify it.

### CODE REVIEW

**Comment by sorawee** [comment]
In Racket, an approach I usually use is to generate a new unique object (via `(gensym)`, `(lambda () #f)`, or even `(cons #f #f)`), use it as the default value, and use `eq?` to test that users do provide arguments.

Does that work here?

**Comment by gamburgm** [comment]
> In Racket, an approach I usually use is to generate a new unique object (via `(gensym)`, `(lambda () #f)`, or even `(cons #f #f)`), use it as the default value, and use `eq?` to test that users do provide arguments.
> 
> Does that work here?

I think some infrastructure would need to change to enable that, you can't provide default values for parameters currently for built-in functions. Not 100% certain though.

**Comment by gamburgm** [comment]
@stchang a `test` submodule is a little tough because `kernel.rkt` calls the FFI. I'll just add tests to `tests/` for now.

**Review by stchang — APPROVED** [review]

**Comment by stchang** [comment]
Thanks!

**Pull request merged**
