### PR TITLE
Add support for Scheme number semantics

### PR DESCRIPTION
**Pull request by kclapper**
This commit adds a compiler flag that enables Scheme number semantics. The flag is off by default, so the default compiler behavior does not change.

Support comes from a scheme numbers library by Danny Yoo. It differs from the eslint style pretty drastically, so the config file was updated to ignore it for now. The eslint version had to be bumped up to make this happen.

Minor refactoring and bug fixes are included. This includes changes to the test fixture to make it easier to add test configurations.

### CODE REVIEW

**Comment by samth** [comment]
Probably this code could be simplified a lot now thanks to the introduction of bignums in JS.

**Comment by kclapper** [comment]
The failing CI tests appear to be issues installing Racket in the test containers. I had a similar issue on my fork and it was resolved just by rerunning the tests. Could someone who has access please manually rerun these tests?

I have a duplicate pull request over on [my fork](https://github.com/kclapper/racketscript/pull/1) showing all the tests passing

**Comment by vishesh** [comment]
Restarted it. I think doing an amend `git commit --amend --no-edit` followed by force push should also re-trigger the CI.

**Comment by kclapper** [comment]
Thank you! That's a smart idea, I'll do that next time 👍

**Comment by vishesh** [comment]
Sorry about slow review. So far looks good. I think using JS's BigNum can be a follow up on top of this? I  presume the scheme number library isn't changed to use BigNum.

**Comment by kclapper** [comment]
No worries 👍 I agree with you and Sam, I actually started working on incorporating BigInt's last week 😄

**Review by vishesh — APPROVED** [review]

**Pull request merged**
